[package]
name = "tipu"
version = "0.1.0"
authors = ["aryaminus <sunim.54@gmail.com>", "GauravRajSharma <blazegaurav123@gmail.com>"]
edition = "2018"

[dependencies]
tuikit = "*"
serde_json = "*"
tui = "0.10"
termion = "1.0.0"
rand = "*"
serde = { version = "1.0", features = ["derive"] }